
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: skylark_development

test:
  <<: *default
  database: skylark_test

production:
  <<: *default
  database: skylark_production
  username: skylark
  password: <%= ENV['SKYLARK_DATABASE_PASSWORD'] %>
